// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsjmwzmujjosfnhewoxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzam13em11ampvc2ZuaGV3b3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTA4ODAsImV4cCI6MjA3MzU2Njg4MH0.WptG8o_PE6OIZpGiwly_0YYzxL0X71MIJysqGYQQZCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});